### ISSUE TITLE
[Enhancement] Change the type of the object in InitGameEvent.

### ISSUE THREAD

**Issue by HuaYuan-Tseng** [Game-as-a-Service/Machi-Koro-Cpp#43]
If use **pointer** to pass the information back  to front-end, perhaps will  **segmentation fault** when call a non-exist  game_id (#41 ).  
  
To separate the concerns of `InitGameEvent` and `InitGamePresenter`, we will modify the pointer type to object type (maybe `std::string` etc.) in `InitGameEvent`.

**Comment by HuaYuan-Tseng** [comment]
Now it can return the error status code normally and would not crash.  
  
<img width="1792" alt="SCR-20240515-ttwu" src="https://github.com/Game-as-a-Service/Machi-Koro-Cpp/assets/55576727/9ff5a303-7405-460a-b293-6ad1c4ab9a1f">

**Comment by angtsusiong** [comment]
#42 Stil Segmentation fault
![image](https://github.com/Game-as-a-Service/Machi-Koro-Cpp/assets/40680513/458accf6-b037-4307-8db0-8e571e3bc662)

**Comment by angtsusiong** [comment]
> #42 Stil Segmentation fault ![image](https://private-user-images.githubusercontent.com/40680513/331416425-458accf6-b037-4307-8db0-8e571e3bc662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDY3MjUsIm5iZiI6MTcxNTkwNjQyNSwicGF0aCI6Ii80MDY4MDUxMy8zMzE0MTY0MjUtNDU4YWNjZjYtYjAzNy00MzA3LThkYjAtOGU1NzFlM2JjNjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAwNDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDZjNjQ4MDRmNmUyMDA0MjA4ZWEyMzY2MGEwNTU5MjMyNDM2NGI4N2E2MzU0Mjk0ZmUwMTliNjQyYmIyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7hHWWTlvDgS6oQpJHRqsJCDH9SaUyZO1ze-wRhprTS4)

![image](https://github.com/Game-as-a-Service/Machi-Koro-Cpp/assets/40680513/aa4c3664-a813-4719-ae15-0e1c8f74f856)

**Comment by HuaYuan-Tseng** [comment]
1. ArchitectureMarket::cards() return std::map<CardName, int>.

**Comment by angtsusiong** [comment]
> 1. `ArchitectureMarket::cards()` return `std::map<CardName, int>`.

```cpp
std::map<CardName, std::vector<Building*>> ArchitectureMarket::cards() const;
```
修改成
```cpp
 std::map<CardName, int> ArchitectureMarket::cards() const;
 ```

因為卡堆不必回傳 `card*` 。當卡片還在卡堆裡，`card::operateEffect` 不會被 call。
